const Data = [
    {
        id: 1,
        img: "./imgs/anpr.png",
        url : "anpr",
        title: "Automatic Number Plate Recognition",
        category : "Image Processing",
        tectStack: ['Python', 'Image Processing', 'OpenCV', 'Tkinter', 'Excel'],
        projectImg : ["../imgs/anpr1.png","../imgs/anpr2.png","../imgs/anpr3.png","../imgs/anpr3.png"],
        github : 'https://github.com/yashwanth0010/ANPR',
        description : ['Designed an application capable of text recognition from provided images of number plates.',
                                'Maintains an up-to-date Excel spreadsheet containing vehicle numbers, states, and timestamps.',
                              'Designed a user friendly interface using Tkinter library.',
                            'Utilized PyInstaller to convert Python code into an executable (EXE) file, ensuring the project’s compatibility and functionality on any system without the need for a Python installation.'
                          ],
      },
      {
        id: 2,
        img: "./imgs/dwiz.png",
        url:"dwiz",
        title: "DWiz",
        category:"Web Application, Data Analysis",
        tectStack: ['R', 'Ggplot', 'Tidyverse', 'ShinyR', 'CSS', 'Bootstrap', 'Shinyapps Cloud'],
        projectImg:[],
        github:"https://github.com/yashwanth0010/DWiz",
        live:"https://datawizard.shinyapps.io/DWiz/",
        description:["Developed a web application for data visualization leveraging R programming language.",
                                "Utilized the most powerful visualization package Ggplot to create compelling data visualizations.",
                              "Built the web interface with ShinyR, employing CSS and Bootstrap for enhanced design and functionality.",
                                "Deployed the project to Shinyapps Cloud platform, enabling live viewing and accessibility."],
      },
      {
        id: 3,
        img: "./imgs/icudp.png",
        url:"icudp",
        title: "Image Captioning using Deep Learning",
        category:"Deep Learning",
        tectStack: ['Python', 'Keras', 'Tensorflow', 'Pillow', 'Deep Learning'],
        projectImg:[],
        github:"https://github.com/yashwanth0010/Image_Caption_Generator",
        description:["Developed an image captioning system using state-of-the-art deep learning techniques, including Convolutional Neural Networks (CNNs) and Recurrent Neural Networks (RNNs).",
                                 "Trained the model on Flicker Dataset comprising high-resolution images paired with corresponding descriptions.",
                                 "Collaborated with a team of 3 to develop the deep learning model for object recognition.",
                                "Employed deep learning techniques, including the Gated Recurrent Unit (GRU), to generate captions."]
      },
      {
        id: 4,
        img: "./imgs/cmp.png",
        url:"cmp",
        title: "College Management Portal",
        category:"Web Development",
        tectStack: ['Python', 'Django', 'MySQL', 'CSS', 'Bootstrap'],
        projectImg:[],
        github:"https://github.com/yashwanth0010/CMS",
        description:["Developed a comprehensive College Management Portal using Django aimed at features such as student enrollment, attendance tracking, grade management and applying for leaves",
                              "Implemented robust data models, integrated database management, and designed secure user authentication and authorization.",
                              "Created distinct login systems for faculty and students, with a specialized mentoring feature connecting students to designated faculty members."]
      },
];
export default Data;